server:
  port: 9000

spring:
  profiles:
    active: @profileActive@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
      config:
        group: DEFAULT_GROUP
        file-extension: properties

  aop:
    auto: true
    proxy-target-class: true

  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

logging:
  config: classpath:logback-spring.xml
  path: /opt/logs/demo-core/