server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        grop: DEFAULT_GROUP
        file-extension: yaml
        prefix: demo

