server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        username: nacos
        password: nacos
        contextPath: /nacos

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

logging:
  config: classpath:logback-spring.xml
  path: /opt/logs/demo-web/

