server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  profiles:
    active: @profileActive@
  application:
    name: web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        prefix: web
        file-extension: yaml

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

logging:
  config: classpath:logback-spring.xml
  path: /opt/logs/demo-web/

